services:
  - type: web
    name: my-python-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    autoDeploy: true
